name: blogy
type: php
docroot: public
php_version: "8.3"
nodejs_version: "24"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173
